services:
  alsabase:
    image: "ghcr.io/alsasoft-web/alsabase:latest"
    container_name: alsabase
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      - PORT=8090
      - NODE_ENV=production
      - "JWT_SECRET=${SERVICE_PASSWORD_JWT}"
      - SERVICE_FQDN_ALSABASE_8090
    volumes:
      - ./data:/app/data
      - ./_hooks:/app/_hooks
      - ./_public:/app/_public
    healthcheck:
      test:
        - CMD
        - wget
        - "--no-verbose"
        - "--tries=1"
        - "--spider"
        - "http://localhost:8090/api/health"
      interval: 30s
      timeout: 5s
      retries: 3
